# Generated by Django 3.2.13 on 2022-11-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_notions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notions',
        ),
    ]
