# Generated by Django 3.2.13 on 2022-11-17 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_articles_category'),
        ('communities', '0003_auto_20221116_1604'),
    ]

    operations = [
    ]
