# Generated by Django 3.2.13 on 2022-11-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20221120_1659'),
        ('accounts', '0003_auto_20221120_1700'),
        ('accounts', '0003_auto_20221120_1701'),
    ]

    operations = [
    ]
