# Generated by Django 3.2.13 on 2022-11-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ten_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
