# Generated by Django 3.2.13 on 2022-11-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='가격등급',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
