# Generated by Django 3.2.13 on 2022-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='NTSC',
            field=models.TextField(blank=True, null=True),
        ),
    ]
