# Generated by Django 3.2.13 on 2022-11-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomments',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcomments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
        migrations.RemoveField(
            model_name='products',
            name='fixed_price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='input_device',
        ),
        migrations.RemoveField(
            model_name='products',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='multimedia',
        ),
        migrations.RemoveField(
            model_name='products',
            name='network',
        ),
        migrations.RemoveField(
            model_name='products',
            name='os',
        ),
        migrations.RemoveField(
            model_name='products',
            name='power_consumption',
        ),
        migrations.RemoveField(
            model_name='products',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='rated_voltage',
        ),
        migrations.RemoveField(
            model_name='products',
            name='security_function',
        ),
        migrations.RemoveField(
            model_name='products',
            name='special_price',
        ),
        migrations.AddField(
            model_name='products',
            name='CPU넘버',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='CPU제조사',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='CPU종류',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='CPU코드명',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='DCI_P3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='D_SUB',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='GPU메모리',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='GPU제조사',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='GPU종류',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='GPU칩셋',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='HDD',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='HDMI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='MicroSD카드',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='NTSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='ODD종류',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='PANTONE',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='RGB라이트',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='SD카드',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='TGP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='TPM',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='UFS',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='USB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='USB_A',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='USB_C',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='miniDP',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='miniLED',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sRGB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='가격',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='게임관련기능',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='게임용',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='고속충전',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='광시야각',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='그래픽작업용',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='돌비비전',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='두께',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='등록년월',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='멀티리더기',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리교체',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리구성',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리대역폭',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리슬롯',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리용량',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리최대용량',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='메모리타입',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='모델명',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='무게',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='무선랜',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='배터리',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='블루투스',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='사무_인강용',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='상품구분',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='셀룰러',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='숫자키패드',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='스레드수',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='슬림형베젤',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='썬더볼트3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='썬더볼트4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='썸네일',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='안전확인인증',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='어댑터',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='얼굴인식',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='운영체제',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='웹캠',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='웹캠OFF지원',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='유선랜',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='이미지1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='이미지2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='이미지3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='저장슬롯',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='저장용량',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='저장장치종류',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='적합성평가인증',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='제조회사',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='제품분류',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='주사율',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='지문인식',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='충전단자',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='코어수',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='쿨링팬',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='키보드라이트',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='터치스크린',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='트루톤',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='패널종류',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='패널표면처리',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='해상도',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='화면밝기',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='화면비율',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='화면크기',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='화면크기대',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='화면회전각',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='휴대용',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Graphics',
        ),
        migrations.DeleteModel(
            name='ProductComments',
        ),
    ]
