# Generated by Django 3.2.13 on 2022-11-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_가격등급'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='GPU종류등급',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='저장용량등급',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='해상도등급',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
