# Generated by Django 3.2.13 on 2022-11-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_저장용량'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='저장용량',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
