# Generated by Django 3.2.13 on 2022-11-15 05:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20221115_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='like_product',
            field=models.ManyToManyField(related_name='like_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
