# Generated by Django 3.2.13 on 2022-11-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_like_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='NTSC',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
