# Generated by Django 3.2.13 on 2022-11-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20221119_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='화면크기등급',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
