# Generated by Django 3.2.13 on 2022-11-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_화면크기등급'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='해상도등급',
            field=models.TextField(blank=True, null=True),
        ),
    ]
