# Generated by Django 3.2.13 on 2022-11-17 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_products_ntsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='AdobeRGB',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='DPAltMode',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='GPU기술',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='MicroHDMI',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='QLED',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='USB_PD',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='리프트힌지',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='전용펜지원',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='침수지연키보드',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='NTSC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('grade', models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('like', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
