# Generated by Django 3.2.13 on 2022-11-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_해상도등급'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='무게등급',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
