# Generated by Django 3.2.13 on 2022-11-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_무게등급'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='CPU제조사분류',
            field=models.TextField(blank=True, null=True),
        ),
    ]
