# Generated by Django 3.2.13 on 2022-11-17 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_ntsc 2'),
        ('products', '0006_merge_0005_alter_products_ntsc_0005_review'),
    ]

    operations = [
    ]
