# Generated by Django 3.2.13 on 2022-11-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_usb_pd'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='MicroHDMI',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
