# Generated by Django 3.2.13 on 2022-11-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_microhdmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='QLED',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
