# Generated by Django 3.2.13 on 2022-11-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_cpu제조사분류'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='CPU넘버분류',
            field=models.TextField(blank=True, null=True),
        ),
    ]
