# Generated by Django 3.2.13 on 2022-11-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='와이드뷰',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='표준텐키리스',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
