# Generated by Django 3.2.13 on 2022-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20221120_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='AppleT2',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
