# Generated by Django 3.2.13 on 2022-11-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_applet2'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='기계식키보드',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
